[2024-12-23T05:47:30.813+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-23T05:47:30.843+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_location_data.upload_airplane_data manual__2024-12-23T05:47:23.796535+00:00 [queued]>
[2024-12-23T05:47:30.851+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_location_data.upload_airplane_data manual__2024-12-23T05:47:23.796535+00:00 [queued]>
[2024-12-23T05:47:30.852+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-12-23T05:47:30.866+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_airplane_data> on 2024-12-23 05:47:23.796535+00:00
[2024-12-23T05:47:30.876+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4282) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-23T05:47:30.878+0000] {standard_task_runner.py:63} INFO - Started process 4284 to run task
[2024-12-23T05:47:30.879+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_location_data', 'upload_airplane_data', 'manual__2024-12-23T05:47:23.796535+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dag_get_current_location.py', '--cfg-path', '/tmp/tmphf84dh8r']
[2024-12-23T05:47:30.880+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask upload_airplane_data
[2024-12-23T05:47:30.931+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_location_data.upload_airplane_data manual__2024-12-23T05:47:23.796535+00:00 [running]> on host d64a5d849547
[2024-12-23T05:47:31.021+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_location_data' AIRFLOW_CTX_TASK_ID='upload_airplane_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T05:47:23.796535+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T05:47:23.796535+00:00'
[2024-12-23T05:47:31.022+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-23T05:47:31.143+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.8.0-1021-aws-x86_64-with-glibc2.36
[2024-12-23T05:47:31.144+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-12-23T05:47:31.827+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-12-23T05:47:33.379+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-12-23T05:47:33.380+0000] {connection.py:762} INFO - closed
[2024-12-23T05:47:33.399+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-12-23T05:47:33.427+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-23T05:47:33.428+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-23T05:47:33.438+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=upload_location_data, task_id=upload_airplane_data, run_id=manual__2024-12-23T05:47:23.796535+00:00, execution_date=20241223T054723, start_date=20241223T054730, end_date=20241223T054733
[2024-12-23T05:47:33.504+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-23T05:47:33.524+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T05:47:33.526+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
